name: Deploy site to AWS EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: rm files
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: rm -rf ~/www/*
          host: 3.16.36.57
          username: ubuntu
          privateKey: ${{ secrets.SSHKEY }}

      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: 3.16.36.57
          username: ubuntu
          key: ${{ secrets.SSHKEY }}
          source: "*"
          target: "/home/ubuntu/www"

      - name: restart nginx
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: sudo systemctl restart nginx
          host: 3.16.36.57
          username: ubuntu
          privateKey: ${{ secrets.SSHKEY}}
