name: Deploy site to AWS EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: print key
        env:
          SSHKEY: ${{ secrets.SSHKEY }}
        run: echo $SSHKEY
      - name: copy static files
        env:
          SSHKEY: ${{ secrets.SSHKEY }}
        run: |
          echo $SSHKEY >> ~/key.pem
          chmod 600 ~/key.pem
          ssh -i ~/key.pem ubuntu@3.16.36.57 'rm -rf ~/www/*'
          scp -i ~/key.pem * ubuntu@3.16.36.57~/www
          ssh -i ~/key.pem ubuntu@3.16.36.57 'sudo systemctl restart nginx'
          rm ~/key.pem
